export const theme = {
  colors: {
    primary: '#8C7D70',
    onPrimary: '#FFFFFF',
    primaryContainer: '#EBE0D5',
    onPrimaryContainer: '#332D27',
    secondary: '#7A7571',
    onSurfaceVariant: '#4A4743',
    background: '#FAFAF8',
    onBackground: '#1A1A19',
    surface: '#FAFAF8',
    onSurface: '#1A1A19',
    outline: '#A39E99',
    outlineVariant: '#CFCAC4',
    surfaceContainerLow: '#F5F3EF',
    surfaceContainer: '#EFEBE6',
    // aliases used across secondary screens
    text: '#1A1A19',
    textSecondary: '#4A4743',
    textMuted: '#A39E99',
    border: '#A39E99',
    accent: '#8C7D70',
  },
  spacing: {
    xs: 4,
    sm: 12,
    base: 8,
    md: 24,
    lg: 40,
    xl: 64,
    margin: 20,
  },
  radius: {
    tile: 20,
    tileFeatured: 24,
    full: 999,
    lg: 20,
    md: 16,
    pill: 999,
  },
  fontSize: {
    labelSm: 12,
    labelMd: 14,
    bodyMd: 16,
    bodyLg: 18,
    headlineMd: 24,
    headlineLg: 28,
    sm: 12,
    md: 16,
    lg: 18,
    xl: 22,
    xxl: 28,
  },
  lineHeight: {
    labelSm: 16,
    labelMd: 20,
    bodyMd: 24,
    bodyLg: 28,
    headlineMd: 32,
    headlineLg: 36,
  },
  fonts: {
    body: 'BeVietnamPro_400Regular',
    bodyMedium: 'BeVietnamPro_500Medium',
    bodySemiBold: 'BeVietnamPro_600SemiBold',
    headline: 'PlusJakartaSans_600SemiBold',
    headlineBold: 'PlusJakartaSans_700Bold',
  },
} as const;
